---
title: "多尺度下物种入侵悖论的复现研究"
author: "跨尺度生态分析小组"
date: "2026-03-18"
output: html_document
---
# 多尺度下物种入侵悖论的复现研究
## 项目成员：
 -梅良2025303120116 
 -师鑫2025303120092

## 加载使用的包
```{r}
library(metafor)
library(plyr)
library(polycor)
library(readr)
library(ggplot2)
```

## 加载数据与数据前处理
```{r}
dat<- read_csv("DataS2_MetaAnalysisDatabase.csv")
dat<-as.data.frame(dat)
dat$abs_Latitude <- abs(dat$Latitude)
```

## 图1及table2中的结果
```{r}
random <- list(~ 1 | Study / Case)
metar <- rma.mv(yi = z, V = var_z, mods = ~ ln_Grain, random = random, data = dat, method = "ML")

###得到图1及table2中的结果
summary(metar)

####计算该分层模型的I2
W <- diag(1/dat$var_z)
X <- model.matrix(metar)
P <- W - W %*% X %*% solve(t(X) %*% W %*% X) %*% t(X) %*% W
100 * sum(metar$sigma2) / (sum(metar$sigma2) + (metar$k-metar$p)/sum(diag(P)))
```

## 论文中图1的制作
```{r}
par(mar=c(5.1,5.1,4.1,2.1))
new_ln_Grain<-seq(from = min(dat$ln_Grain),to = max(dat$ln_Grain), length = 204)
preds <- predict(metar, newmods=new_ln_Grain)
wi<- 1/dat$var_z
wi <- na.omit(wi)
size  <-1+ 5.0 * (wi - min(wi))/(max(wi) - min(wi))

plot(dat$ln_Grain, dat$z, pch=1, cex=size, col="black",
         xlab="ln(grain size)", ylab="Fisher’s z",
         las=1, bty="l", font=2,cex.lab=1.5)
points(dat$ln_Grain, dat$z, pch=16, cex=0.1)
lines(new_ln_Grain, preds$pred,col="red")
abline(h=0, lty="dotted",col="black",lwd=2)
lines(new_ln_Grain, preds$ci.lb, lty="dashed",lwd=2,col="red")
lines(new_ln_Grain, preds$ci.ub, lty="dashed",lwd=2,col="red")
text(c(10), -1.5, c("Qm=33.83,df=1,P<0.0001"),cex=1.3,font=1,col="red")
```


## table2中habitat及Fig2B结果
```{r}
pairs(~ abs_Latitude + Longitude + ln_Grain, data = dat)
dat$Habitat_type<-as.factor(dat$Habitat_type)
dat$Extent<-as.ordered(dat$Extent)

hetcor(data = dat[, c("ln_Grain", "abs_Latitude", "Longitude", "Extent", "Habitat_type")], std.err = FALSE)

lat <- rma.mv(yi = z, V = var_z, mods = ~ abs_Latitude, random = random, data = dat, method = "ML")
lon2 <- rma.mv(yi = z, V = var_z, mods = ~ Longitude + I(Longitude^2), random = random, data = dat, method = "ML")
ext <- rma.mv(yi = z, V = var_z, mods = ~ -1 + Extent, random = random, data = dat, method = "ML")
ext.ord <- rma.mv(yi = z, V = var_z, mods = ~ ordered(Extent), random = random, data = dat, method = "ML")
summary(ext.ord)

subset.hab <- dat[which(dat$Habitat_type != "many"), ]
hab.full <- rma.mv(yi = z, V = var_z, mods = ~ -1 + Habitat_type, random = random, data = dat, method = "ML")
hab <- rma.mv(yi = z, V = var_z, mods = ~ -1 + Habitat_type, random = random, data = subset.hab, method = "ML")
hab.Q <- rma.mv(yi = z, V = var_z, mods = ~ Habitat_type, random = random, data = subset.hab, method = "ML")
summary(hab.Q)

###I2的计算
W <- diag(1/subset.hab$var_z)
X <- model.matrix(hab.Q)
P <- W - W %*% X %*% solve(t(X) %*% W %*% X) %*% t(X) %*% W
100 * sum(hab.Q$sigma2) / (sum(hab.Q$sigma2) + (hab.Q$k-hab.Q$p)/sum(diag(P)))
```

## Fig.2b作图
```{r}
coef(summary(hab))
estimates4 <- coef(summary(hab))[,1]
se4 <- coef(summary(hab))[,2]
variances4<- se4^2

dd1<-as.data.frame(table(subset.hab$Habitat_type))

samplesize<-as.data.frame(dd1$Freq)
samplesize<-samplesize[-4,]
labels4 <- c("Agricultural", "Forest", "Grassland", "Shrubland", "Urban", "Wetland")
dat2<-as.data.frame(cbind(labels4,estimates4,se4))

dat2$estimates4 <- as.numeric(as.character(dat2$estimates4))
dat2$se4 <- as.numeric(as.character(dat2$se4))
dat2$samplesize <- samplesize

ggplot(dat=dat2,aes(x=labels4, y=estimates4))+geom_point()+
geom_errorbar(aes(ymin=estimates4-1.96*se4, 
                  ymax=estimates4+1.96*se4), 
              width=.2)+
             theme_bw() + 
             labs(x="Habitat",y="Fisher's Z")+
             scale_y_continuous(breaks = seq(-0.2, 1.2, by = 0.2))+
             theme(panel.border = element_blank(), 
             panel.grid.major = element_blank(),
             panel.grid.minor = element_blank(), 
             axis.line = element_line(colour = "black"))+
             theme(axis.text=element_text(size=16),
             axis.title=element_text(size=16,face="bold"))+
             geom_hline(yintercept =0)+
  geom_text(aes(label=samplesize), hjust=1.5)
```

## Fig.S1作图

```{r}
randomonly <- rma.mv(yi = z, V = var_z, random = random, data = dat, method = "REML")
randomonly2 <- rma(yi = z, vi = var_z, data = dat)
funnel(randomonly2, level=c(90, 95, 99),
       shade=c("white", "gray", "darkgray"), refline=0,
       main="Standard Error")
abline(v=randomonly$b, lty="solid",col="red",lwd=2)
```








